name: core
version: 0.0.1
publish_to: none
description: Project core module

environment:
  sdk: '>=3.8.0 <4.0.0'
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  navigation:
    path: ../navigation

  get_it: ^8.2.0
  dio: ^5.9.0
  logger: ^2.6.1
  flutter_bloc: ^9.1.1
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  json_serializable: ^6.11.1
  flutter_gen: ^5.11.0

flutter:
  uses-material-design: true
  assets:
    - resources/
    - resources/translations/
