name: features
version: 0.0.1
publish_to: none
description: features module

environment:
  sdk: '>=3.8.0 <4.0.0'
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  core_ui:
    path: ../core_ui
  domain:
    path: ../domain
  auto_route: ^10.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.0
