name: core_ui
version: 0.0.1
publish_to: none
description: Project Core UI module

environment:
  sdk: '>=3.8.0 <4.0.0'
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  domain:
    path: ../domain
  navigation:
    path: ../navigation

dev_dependencies:
  flutter_lints: ^6.0.0
